### ISSUE TITLE
Drawing more complicated PV systems often fails

### ISSUE THREAD

**Issue by FlorianK13** [open-pv/website#210]
In this example I wanted to add a polygon as PV system for the whole roof. It somehow connected the dots to form a polygon I had not in mind. Maybe we should need to take the order of added PV edge points into account? This would be the intuitive way that people draw PV edges one after another.

In this screenshot some PV edges were even ignored, which is another issue by itself 😒 

![grafik](https://github.com/user-attachments/assets/1339e5d9-2387-4e78-840a-6ee408c51700)

**Comment by FlorianK13** [comment]
If only someone like @khdlr studied mathematics. Because after spending two minutes on this problem I think it is not trivial to solve. We have the edge points clicked in the order that the user wants the PV system to be:
![grafik](https://github.com/user-attachments/assets/d1968743-b124-434c-abd8-9758c7b37cee)
Afterwards, the list of points is converted to triangles, but without using knowledge about what is inside the pv system and what is outside:
![grafik](https://github.com/user-attachments/assets/6b66f8bd-4364-47de-b044-a4268a626924)
I assume that adding up angles should tell us what is inside and outside, right?

**Comment by khdlr** [comment]
> If only someone like @khdlr studied mathematics.

Always up for some good geometry shenanigans :wink:

**Comment by FlorianK13** [comment]
This was solved by the merged PR
