### ISSUE TITLE
Highlight results of earnings calculation

### ISSUE THREAD

**Issue by FlorianK13** [open-pv/website#265]
After users have calculated an earing, they often do not see the results, as they are not really highlighted. We could have a colorful box that appears within the modal or create a new modal.

**Comment by FlorianK13** [comment]
I think a colorful box within the existing modal is better. Otherwise we have too many modals flying around on the website.

**Comment by MartGro** [comment]
Yes, or a colorful frame around the calculation and a toast, to have two visual cues
